# azure-pipelines.yml - configuration for Azure Pipelines
# Copyright (C) 2020 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
variables:
  deploy.azureSubscription: linuxfront-csave-audio
  deploy.appName: linuxfront-csave-audio
trigger:
  - master
stages:
  - stage: Default
    jobs:
      - job: Package
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: |
              cp -r * $(Build.BinariesDirectory)/
            displayName: Copy contents
          - task: ArchiveFiles@2
            inputs:
              includeRootFolder: false
          - publish: $(Build.ArtifactStagingDirectory)
            artifact: app
  - stage: Deployment
    dependsOn:
      - Default
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: $(deploy.appName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: $(deploy.azureSubscription)
                    appType: webApp
                    appName: $(deploy.appName)
                    package: .
                    deploymentMethod: zipDeploy
